In [1]:
import pandas as pd

In [2]:
#reading and showing dataframe
df=pd.read_csv("StudentsPerformance.csv")
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

# Create Index

In [3]:
import numpy as np
import random

In [4]:
#creating non repetative values for the index
new_index=np.arange(0,1000)

In [5]:
# shuffling the indexes
random.shuffle(new_index)

In [6]:
# create a new column with new index
df['new index']=new_index

In [7]:
# show thw dataframe
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,new index
0,female,group B,bachelor's degree,standard,none,72,72,74,41
1,female,group C,some college,standard,completed,69,90,88,191
2,female,group B,master's degree,standard,none,90,95,93,104
3,male,group A,associate's degree,free/reduced,none,47,57,44,28
4,male,group C,some college,standard,none,76,78,75,607
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,853
996,male,group C,high school,free/reduced,none,62,55,55,526
997,female,group C,high school,free/reduced,completed,59,71,65,552
998,female,group D,some college,standard,completed,68,78,77,456
999,female,group D,some college,free/reduced,none,77,86,86,349

# 2 set_index()
The set_index() method in pandas is used to set one or more existing columns of a DataFrame as its index (row labels).

**📌 Basic Syntax**:

DataFrame.set_index(keys, drop=True, inplace=False)


**🔑 Parameters**:

**keys**: Column name(s) you want to set as the index.

**drop (default True)**: Removes the column(s) used as the new index

**inplace (default False)**: Modifies the original DataFrame if True

In [8]:
# set new index as the row label (index) and modify the original dataframe
df.set_index('new index',inplace=True)
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
new index,,,,,,,,
41,female,group B,bachelor's degree,standard,none,72,72,74
191,female,group C,some college,standard,completed,69,90,88
104,female,group B,master's degree,standard,none,90,95,93
28,male,group A,associate's degree,free/reduced,none,47,57,44
607,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
853,female,group E,master's degree,standard,completed,88,99,95
526,male,group C,high school,free/reduced,none,62,55,55
552,female,group C,high school,free/reduced,completed,59,71,65
456,female,group D,some college,standard,completed,68,78,77
349,female,group D,some college,free/reduced,none,77,86,86

# 3 sort_index()