In [1]:
import pandas as pd

In [2]:
#reading and showing dataframe
df=pd.read_csv("StudentsPerformance.csv")
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

# Create Index

In [3]:
import numpy as np
import random

In [5]:
#creating non repetative values for the index
new_index=np.arange(0,1000)

In [6]:
# shuffling the indexes
random.shuffle(new_index)

In [8]:
# create a new column with new index
df['new index']=new_index

In [10]:
# show thw dataframe
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,new index
0,female,group B,bachelor's degree,standard,none,72,72,74,282
1,female,group C,some college,standard,completed,69,90,88,844
2,female,group B,master's degree,standard,none,90,95,93,130
3,male,group A,associate's degree,free/reduced,none,47,57,44,140
4,male,group C,some college,standard,none,76,78,75,587
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,897
996,male,group C,high school,free/reduced,none,62,55,55,578
997,female,group C,high school,free/reduced,completed,59,71,65,457
998,female,group D,some college,standard,completed,68,78,77,317
999,female,group D,some college,free/reduced,none,77,86,86,979