In [1]:
import pandas as pd

In [3]:
# reading the csv
df=pd.read_csv("StudentsPerformance.csv")
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

# 1. Adding a column

 ## 1.1 Adding a new column with a scalar value

In [5]:
# adding a new column to dataframe
df['language score']=70 # new column "language score" created and al rows have same value 
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,70
1,female,group C,some college,standard,completed,69,90,88,70
2,female,group B,master's degree,standard,none,90,95,93,70
3,male,group A,associate's degree,free/reduced,none,47,57,44,70
4,male,group C,some college,standard,none,76,78,75,70
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,70
996,male,group C,high school,free/reduced,none,62,55,55,70
997,female,group C,high school,free/reduced,completed,59,71,65,70
998,female,group D,some college,standard,completed,68,78,77,70
999,female,group D,some college,free/reduced,none,77,86,86,70

## 1.2 Adding a new column with an array
The DataFrame has 1000 elements, so we need to create an array with 1000 elemnts

In [6]:
#import numpy
import numpy as np

In [10]:
# create an array of 1000 elements
language_score=np.arange(0,1000,1)
type(language_score)

numpy.ndarray

In [11]:
#length of the array
len(language_score)

1000

In [ ]:
# adding a new column to dataframe with an array
df['langauge score']=langauge_