In [1]:
#importing libraries
import pandas as pd
import numpy as np

# 1.Creating a DATAFRAME from an array

In [2]:
# creating the array
arr=np.array([[1,2],[2,3],[4,5]])
arr

array([[1, 2],
       [2, 3],
       [4, 5]])

In [4]:
#creating a datafarme
pd.DataFrame(arr)

   0  1
0  1  2
1  2  3
2  4  5

In [8]:
# creating DataFrame with customized row(index) and columns name
df=pd.DataFrame(arr,index=['row1','row2','row3'],columns=['col1','col2'])
df

      col1  col2
row1     1     2
row2     2     3
row3     4     5

# Creating DataFrame using Dictionary

In [9]:
# List used for this example
states=['California','Texas','Florida','New York']
population=[12345678,98765392,89146738,56382913]

In [ ]:
#creating dictionary
dict_states={'states':states,

In [15]:
# creating DataFrame using Dictionary
df=pd.DataFrame({'States':states,'Population':population})
df

       States  Population
0  California    12345678
1       Texas    98765392
2     Florida    89146738
3    New York    56382913