In [1]:
#importing libraries
import pandas as pd
import numpy as np

# 1.Creating a DATAFRAME from an array

In [2]:
# creating the array
arr=np.array([[1,2],[2,3],[4,5]])
arr

array([[1, 2],
       [2, 3],
       [4, 5]])

In [4]:
#creating a datafarme
pd.DataFrame(arr)

   0  1
0  1  2
1  2  3
2  4  5

In [6]:
# creating DataFrame with customized row(index) and columns name
pd.DataFrame(arr,index=['row1','row2','row3'],columns=['col1','col2'])

      col1  col2
row1     1     2
row2     2     3
row3     4     5