In [1]:
#importing libraries
import pandas as pd
import numpy as np

# 1.Creating a DATAFRAME from an array

In [2]:
# creating the array
arr=np.array([[1,2],[2,3],[4,5]])
arr

array([[1, 2],
       [2, 3],
       [4, 5]])

In [4]:
#creating a datafarme
pd.DataFrame(arr)

   0  1
0  1  2
1  2  3
2  4  5

In [8]:
# creating DataFrame with customized row(index) and columns name
df=pd.DataFrame(arr,index=['row1','row2','row3'],columns=['col1','col2'])
df

      col1  col2
row1     1     2
row2     2     3
row3     4     5

# Creating DataFrame using Dictionary

In [9]:
# List used for this example
states=['California','Texas','Florida','New York']
population=[12345678,98765392,89146738,56382913]

In [16]:
#creating dictionary
dict_states={'States':states,'Population':population}

In [17]:
# creating DataFrame using Dictionary
df_population=pd.DataFrame(dict_states)
df

       States  Population
0  California    12345678
1       Texas    98765392
2     Florida    89146738
3    New York    56382913

# Creating Dataframe From CSV files

In [24]:
# reading the csv file
df_csv=pd.read_csv("StudentsPerformance.csv")

In [25]:
# showing first 5 rows
df_csv.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75