In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("StudentsPerformance.csv")
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

# 1. Selecting two or more columns

In [3]:
# select 2 colums using [[]]
df[['gender','lunch']]

     gender         lunch
0    female      standard
1    female      standard
2    female      standard
3      male  free/reduced
4      male      standard
..      ...           ...
995  female      standard
996    male  free/reduced
997  female  free/reduced
998  female      standard
999  female  free/reduced

[1000 rows x 2 columns]

In [4]:
# check datatype of the selection
type(df[['gender','lunch']])

pandas.core.frame.DataFrame

In [5]:
# select 2 or more columns usjing [[]]
df[['gender','lunch','math score']]

     gender         lunch  math score
0    female      standard          72
1    female      standard          69
2    female      standard          90
3      male  free/reduced          47
4      male      standard          76
..      ...           ...         ...
995  female      standard          88
996    male  free/reduced          62
997  female  free/reduced          59
998  female      standard          68
999  female  free/reduced          77

[1000 rows x 3 columns]

In [6]:
# we can't select 2 or more columns with the "."
df.gender.lunch

AttributeError: 'Series' object has no attribute 'lunch'