In [1]:
import pandas as pd

In [2]:
# reading the csv
df=pd.read_csv("StudentsPerformance.csv")
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

# 1. Adding a column

 ## 1.1 Adding a new column with a scalar value

In [3]:
# adding a new column to dataframe
df['language score']=70 # new column "language score" created and al rows have same value 
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,70
1,female,group C,some college,standard,completed,69,90,88,70
2,female,group B,master's degree,standard,none,90,95,93,70
3,male,group A,associate's degree,free/reduced,none,47,57,44,70
4,male,group C,some college,standard,none,76,78,75,70
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,70
996,male,group C,high school,free/reduced,none,62,55,55,70
997,female,group C,high school,free/reduced,completed,59,71,65,70
998,female,group D,some college,standard,completed,68,78,77,70
999,female,group D,some college,free/reduced,none,77,86,86,70

## 1.2 Adding a new column with an array
The DataFrame has 1000 elements, so we need to create an array with 1000 elemnts

In [4]:
#import numpy
import numpy as np

In [5]:
# create an array of 1000 elements
language_score=np.arange(0,1000,1)
type(language_score)

numpy.ndarray

In [6]:
#length of the array
len(language_score)

1000

In [7]:
# adding a new column to dataframe with an array
df['language score']=language_score
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,0
1,female,group C,some college,standard,completed,69,90,88,1
2,female,group B,master's degree,standard,none,90,95,93,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,3
4,male,group C,some college,standard,none,76,78,75,4
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,995
996,male,group C,high school,free/reduced,none,62,55,55,996
997,female,group C,high school,free/reduced,completed,59,71,65,997
998,female,group D,some college,standard,completed,68,78,77,998
999,female,group D,some college,free/reduced,none,77,86,86,999

### Random numbers

In [8]:
# Create Random Integer Numbers Between 1 and 100
int_language_score=(np.random.randint(low=1,high=100,size=1000))

In [9]:
#min value inclusive and high value exclusive
print(min(int_language_score))
print(max(int_language_score))

1
99

In [10]:
# adding a new column to dataframe with an array
df['language score']=int_language_score
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,82
1,female,group C,some college,standard,completed,69,90,88,27
2,female,group B,master's degree,standard,none,90,95,93,22
3,male,group A,associate's degree,free/reduced,none,47,57,44,50
4,male,group C,some college,standard,none,76,78,75,59
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,81
996,male,group C,high school,free/reduced,none,62,55,55,58
997,female,group C,high school,free/reduced,completed,59,71,65,3
998,female,group D,some college,standard,completed,68,78,77,67
999,female,group D,some college,free/reduced,none,77,86,86,6

In [13]:
#create random float numbers between 1 and 100
np.random.uniform(1,100,size=100)

array([95.54906113, 34.94971201, 88.62668822, 36.90120837, 51.83875823,
       67.68622681, 94.19357875, 96.89934474, 22.42936226, 15.16683291,
       84.3501472 , 31.00707327, 24.82462806, 78.16648818, 62.64688226,
       98.84412613, 38.24538442, 11.00440794, 27.89519875, 64.2744051 ,
       82.27100738, 88.75708728, 76.6067808 , 86.20939811, 53.40631001,
       71.23729615, 53.18193245, 91.52416704, 86.2580362 , 31.58480782,
       90.29842322, 59.72720335, 29.76756448, 75.96932886, 23.55298819,
       69.63184692, 71.94646678, 16.6242063 , 12.25963407, 19.5891826 ,
       25.14918611, 98.20457513, 30.75358244, 19.85134432, 56.58849734,
       34.17103784, 90.93662202, 79.63458753, 70.74833995, 85.80939478,
       91.03775087, 35.61191071, 53.70740408, 32.78614823, 94.68835957,
       70.33658807, 41.28036305, 42.78681484, 64.20829971,  5.11362081,
       67.71134789, 66.92302889, 94.35372628, 18.11731593, 39.21758397,
       60.34680761, 44.17267043, 92.6868455 , 53.68290729, 55.66572112,
       56.7415922 , 90.05252032, 46.23627729, 96.31716681, 90.0422043 ,
       53.35297317, 62.87367721, 40.85857349, 23.43275407, 96.44068028,
       77.42119857, 68.2458309 , 14.36468937, 44.79953693, 67.75029648,
       18.17468156, 17.41644605, 84.83965863, 69.86678317, 50.64371341,
       41.10132784, 60.38329617, 98.07911698,  6.0689407 , 58.19363819,
       15.3860341 , 15.91240166, 88.39380145, 92.16637742, 47.79114369])