In [1]:
import pandas as pd

In [2]:
#read csv file
df=pd.read_csv('players_20.csv')

#set index
df.set_index('short_name',inplace=True)

#set columns
df=df[['long_name','age','dob','height_cm','weight_kg','nationality','club']]

In [3]:
df.head(3)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain

# 1 Set value to one cell

In [4]:
# update L. Messi height
df.loc['L. Messi','height_cm']=175

In [5]:
# show dataframe
df.head(3)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,175,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain

# 2 Set Value to entrie column

In [6]:
# set height of all players to 190
df.loc[:,'height_cm']=190

In [7]:
# show dataframe
df.head(3)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,190,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,190,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,190,68,Brazil,Paris Saint-Germain

# Set value to entire row

In [8]:
# get all columns that correspond to player ranked last in fifa
len(df)

df.iloc[-1,:]

long_name                         潘喜明
age                                26
dob                        1993-01-11
height_cm                         190
weight_kg                          78
nationality                  China PR
club           Hebei China Fortune FC
Name: Pan Ximing, dtype: object

In [9]:
# set null values to all columns that corresponds to player ranked last in fifa
import numpy as np

df.iloc[-1,:]=np.nan

In [10]:
# show dataframe
df.iloc[-1,:]

long_name      NaN
age            NaN
dob            NaN
height_cm      NaN
weight_kg      NaN
nationality    NaN
club           NaN
Name: Pan Ximing, dtype: object

# 4 Set value to Multiple cells

In [12]:
# set value for all items matching the list of labels
df.loc[['L. Messi','Cristiano Ronaldo'],'height_cm']=175

In [13]:
#show dataframe
df.head(2)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32.0,1987-06-24,175.0,72.0,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34.0,1985-02-05,175.0,83.0,Portugal,Juventus

# 5 set values for rows matching a condition

In [19]:
# set values for rows matching a condition
columns=['age','dob','height_cm','weight_kg']

# select only those rows with height above 180 cm
df['height_cm']>180

df.loc[df['height_cm']>180,columns]=0

In [20]:
#show dataframe
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32.0,1987-06-24,175.0,72.0,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34.0,1985-02-05,175.0,83.0,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,0.0,0,0.0,0.0,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,0.0,0,0.0,0.0,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,0.0,0,0.0,0.0,Belgium,Real Madrid